# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
	desc "Runs test pipeline"
    lane :run_tests_pipeline do
    	android_home
    	local_properties
        run_test
    end

    desc "Creates local properties file"
    lane :android_home do 
    	sh("export", "PATH=$PATH:/Users/<username>/Library/Android/sdk/tools")
    	sh("export", "PATH=$PATH:/Users/<username>/Library/Android/sdk/platform-tools")
    end

    desc "Creates local properties file"
    lane :local_properties do 
    	sh("touch", "../local.properties")
    end

    desc "Runs all the tests"
    lane :run_test do
        gradle(
            task: "test"
        )
    end

end
